#
# Maintainer:   jeffskinnerbox@yahoo.com / www.jeffskinnerbox.me
# Version:      0.0.0
#
# Snippet Box is a simple self-hosted app for organizing your code snippets.
# It supports Markdown documentation for companion notes or simple documentation for your code.
# It it makes it easily to create, edit, browse, and manage your snippets in various languages.
#
# to start this docker container for ubuntu desktop
#    cd ~/src/snippet-box
#
## start the snippet-box docker container via docker-compose
#    sudo SNIPPET_PORT=5000 SNIPPET_DATA='./data' \
#         docker-compose up -d --file ./snippet-box-docker-compose.yml
#


version: '3'
services:
  snippet-box:
    container_name: snippet-box
    image: pawelmalak/snippet-box:latest
    volumes:
      - ${SNIPPET_PATH}:/app/data
    ports:
      - ${SNIPPET_PORT}:5000
    restart: unless-stopped
